app/urls.py
from django.conf.urls import url
import views


urlpatterns=[
	url(r'^$',views.dashboard,name="dashboard"),
	url(r'^view-notifications/$',views.view_notifications,name='view_notifications'),
	url(r'^mark-as-read/(?P<pk>.*)/$',views.mark_as_read,name='mark_as_read'),
	url(r'^mark-as-not-read/(?P<pk>.*)/$',views.mark_as_not_read,name='mark_as_not_read'),
	url(r'^search-result/$',views.search_result,name='search_result'),
	url(r'^mark-as-deleted/(?P<pk>.*)/$',views.mark_as_deleted,name='mark_as_deleted'),
]

customers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from customers.autocomplete_light_registry import CustomerAutocomplete
from customers.models import Customer
from django.views import generic


urlpatterns = [               
    
    url(r'^create-customer/$',views.create_customer,name='create_customer'),
    url(r'^view-customers/$',views.view_customers,name='view_customers'),
    url(r'^edit-customer/(?P<pk>.*)/$',views.edit_customer,name='edit_customer'),
    url(r'^view-customer/(?P<pk>.*)/$',views.view_customer,name='view_customer'),
    url(r'^delete-customer/(?P<pk>.*)/$',views.delete_customer,name='delete_customer'),
    url(r'^customer-autocomplete/$',CustomerAutocomplete.as_view(), name='customer-autocomplete',),
    url(r'^create-customer-popup/$',views.create_customer_popup,name='create_customer_popup'),
]

offroad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls import (
handler400, handler403, handler404, handler500
)


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^',include('app.urls',namespace='dashboard')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^shops/',include('shops.urls',namespace='shops')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^customers/',include('customers.urls',namespace='customers')),
    url(r'^purchases/',include('purchases.urls',namespace='purchases')),
    url(r'^vendors/',include('vendors.urls',namespace='vendors')),
    url(r'^sales/',include('sales.urls',namespace='sales')),
    url(r'^reports/',include('reports.urls',namespace='reports')),
    url(r'^app/',include('app.urls',namespace='app')),
    url(r'^expense/',include('expense.urls',namespace='expense')),
    url(r'^cheque-details/',include('cheques.urls',namespace='cheques')),
    
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT,}),
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT,}),
]

handler400 = "app.views.handler400"
handler403 = "app.views.handler403"
handler404 = "app.views.handler404"
handler500 = "app.views.handler500"

products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from products.autocomplete_light_registry import ProductAutocomplete


urlpatterns = [               
    
    url(r'^create-product/$',views.create_product,name='create_product'),
    url(r'^view-products/$',views.view_products,name='view_products'),
    url(r'^edit-product/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^view-product/(?P<pk>.*)/$',views.view_product,name='view_product'),
    url(r'^delete-product/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product-autocomplete/$',ProductAutocomplete.as_view(), name='product-autocomplete',),
    url(r'^create-product-popup/$',views.create_product_popup,name='create_product_popup'),
]

vendors/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from vendors.autocomplete_light_registry import VendorAutocomplete


urlpatterns = [
    url(r'^create-vendor/$', views.create_vendor, name='create_vendor'),
    url(r'^view-vendor/(?P<pk>.*)/$', views.view_vendor, name='view_vendor'),
    url(r'^edit-vendor/(?P<pk>.*)/$', views.edit_vendor, name='edit_vendor'),
    url(r'^view-vendors/$', views.view_vendors, name='view_vendors'),  
    url(r'^delete-vendor/(?P<pk>.*)/$', views.delete_vendor, name='delete_vendor'),
    url(r'^vendor-autocomplete/$',VendorAutocomplete.as_view(), name='vendor-autocomplete',),
    url(r'^create-vendor-popup/$', views.create_vendor_popup, name='create_vendor_popup'),
]

templates/app/search_result.html
{% extends "base.html" %}
{% load i18n %}


{% block headerbar %}
    <div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
    </div>
{% endblock %}

{% block content %}
                
        {% if product_instances %}
            <h4 class="col-sm-12"><b>{{title1}}</b></h4>
            <div class="clearfix"></div>
            <div class="table-responsive">
                <table id="data-table-basic" class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Stock</th>
                            <th>Price</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in product_instances %}
                            <tr class="">
                                <td><a href="{% url 'products:view_product' pk=instance.pk %}">{{instance.name}}</a></td>
                                <td>{{instance.stock}}</td>
                                <td>{{instance.unit_price|default:"-"}}</td>
                                <td>{{instance.description|default:"-"}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>   
        {% endif %}                       
                
        {% if vendor_instances %}
            <h4 class="col-sm-12"><b>{{title2}}</b></h4>
            <div class="clearfix"></div>
            <div class="table-responsive">
                <table  class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Address</th>
                            <th>Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in vendor_instances %}
                            <tr class="">
                                <td><a href="{% url 'vendors:view_vendor' pk=instance.pk %}">{{instance.name}}</a></td>
                                <td>{{instance.phone|default:"-"}}</td>
                                <td>{{instance.address|default:"-"}}</td>
                                <td>{{instance.balance}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>   
        {% endif %}                       
                
        {% if customer_instances %}
            <h4 class="col-sm-12"><b>{{title3}}</b></h4>
            <div class="clearfix"></div>
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-vmiddle">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Address</th>
                            <th>Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in customer_instances %}
                            <tr class="">
                                <td><a href="{% url 'customers:view_customer' pk=instance.pk %}">{{instance.name}}</a></td>
                                <td>{{instance.phone|default:"-"}}</td>
                                <td>{{instance.address|default:"-"}}</td>
                                <td>{{instance.balance}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}    
        
        {% if not product_instances and not customer_instances and not vendor_instances %}
            {% include 'includes/not_found.html' %}
        {% endif %}                     
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}

templates/app/view_notifications.html
{% extends "base.html" %}
{% load i18n %}


{% block headerbar %}
    <div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
    </div>
{% endblock %}

{% block filter %}
    <div id="filter" class="col-sm-3 col-md-2 collapse width">
        <div class="filter-content">
            <form action="{% url 'app:view_notifications' %}">
                <div class="row">
                    <label class="col-xs-12" for="filter_q">Query</label>
                    <input id="filter_q" type="text" name="q" placeholder="Enter Query..."/>
                </div>
                <section class="submitContainer">
                    <input type="submit" value="Filter" class="btn btn-primary" />
                </section>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}

    {% if message %}
        <div class="alert alert-success alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{message}}
        </div>
    {% endif %}

    <div class="card">
                
        {% if instances %}
            
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-vmiddle">
                    <thead>
                        <tr>
                            <th>Message</th>
                            <th>Time</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in instances %}
                            {% if instance.is_read %}
                                <tr class="check_items_row read">
                                    <td>{{instance.message|safe}}</td>
                                    <td>{{instance.time}}</td>
                                    <td>
                                        <a href="{% url 'app:mark_as_not_read' pk=instance.pk %}" type="submit" class="">Mark as not read</a>
                                    </td>
                                    {% if not instance.is_deleted %}
                                        <td>
                                            <a href="{% url 'app:mark_as_deleted' pk=instance.pk %}" type="submit" class="">Delete</a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% else %}
                                <tr class="check_items_row not_read">
                                    <td>{{instance.message|safe}}</td>
                                    <td>{{instance.time}}</td>
                                    <td class="">
                                        <a href="{% url 'app:mark_as_read' pk=instance.pk %}" type="submit" class="">Mark as read</a>
                                    </td>
                                    {% if not instance.is_deleted %}
                                        <td>
                                            <a href="{% url 'app:mark_as_deleted' pk=instance.pk %}" type="submit" class="">Delete</a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>   
        {% else %}
            {% include 'includes/not_found.html' %}
        {% endif %}                       
    </div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}