app/urls.py
from django.conf.urls import url
import views


urlpatterns=[
	url(r'^$',views.dashboard,name="dashboard"),
	url(r'^view-notifications/$',views.view_notifications,name='view_notifications'),
	url(r'^mark-as-read/(?P<pk>.*)/$',views.mark_as_read,name='mark_as_read'),
	url(r'^mark-as-not-read/(?P<pk>.*)/$',views.mark_as_not_read,name='mark_as_not_read'),
	url(r'^search-result/$',views.search_result,name='search_result'),
	url(r'^mark-as-deleted/(?P<pk>.*)/$',views.mark_as_deleted,name='mark_as_deleted'),
]

offroad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls import (
handler400, handler403, handler404, handler500
)


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^',include('app.urls',namespace='dashboard')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^shops/',include('shops.urls',namespace='shops')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^customers/',include('customers.urls',namespace='customers')),
    url(r'^purchases/',include('purchases.urls',namespace='purchases')),
    url(r'^vendors/',include('vendors.urls',namespace='vendors')),
    url(r'^sales/',include('sales.urls',namespace='sales')),
    url(r'^reports/',include('reports.urls',namespace='reports')),
    url(r'^app/',include('app.urls',namespace='app')),
    url(r'^expense/',include('expense.urls',namespace='expense')),
    url(r'^cheque-details/',include('cheques.urls',namespace='cheques')),
    
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT,}),
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT,}),
]

handler400 = "app.views.handler400"
handler403 = "app.views.handler403"
handler404 = "app.views.handler404"
handler500 = "app.views.handler500"

products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from products.autocomplete_light_registry import ProductAutocomplete


urlpatterns = [               
    
    url(r'^create-product/$',views.create_product,name='create_product'),
    url(r'^view-products/$',views.view_products,name='view_products'),
    url(r'^edit-product/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^view-product/(?P<pk>.*)/$',views.view_product,name='view_product'),
    url(r'^delete-product/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product-autocomplete/$',ProductAutocomplete.as_view(), name='product-autocomplete',),
    url(r'^create-product-popup/$',views.create_product_popup,name='create_product_popup'),
]

templates/products/entry_product.html
{% extends "base.html" %}
{% load i18n %}

{% block headerbar %}
	<div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
    </div>
{% endblock %}

{% block content %}
	{% if errors %}
		<div class="alert alert-danger">
		  <strong>Error!</strong> 
		    {{errors | safe}}
		</div>
	{% endif %}
	
	<form action="{{ url }}" method="post" class="form-horizontal">
		{% csrf_token %}
		{% for field in form %}
		  <div class="form-group {% if field.errors %} has-error {% endif %}">
		    <label class="control-label col-sm-2" for="{{field.id_for_label}}">{{field.label}} :</label>
		    <div class="col-sm-8">
		      {{field}}
		    </div>
		  </div>
		  {% if field.help_text %}
	        <p class="help">{{ field.help_text|safe }}</p>
	      {% endif %}
		{% endfor %}
		{% if current_user_profile.tax_only == False %}
			<div class="form-group ">
			    <label class="control-label col-sm-2" for="id_untaxed">Untaxed :</label>
			    <div class="col-sm-8">
			      <input id="id_untaxed" name="untaxed" type="checkbox" />
			    </div>
			 </div>
		 {% endif %}
		<div class="form-group"> 
		    <div class="col-sm-offset-2 col-sm-10">
		    	<button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
	</form>
{% endblock %}

{% block static %}
	{% load static %}
	<script>
		$('input[type=text]').focus(function () { 
                $(this).select();
            });
	</script>
{% endblock %}

templates/products/view_product.html
{% extends "base.html" %}
{% load i18n %}


{% block headerbar %}
	<div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-6 col-sm-4">{{title}}</h4>

        {% if admin %}
         <div class="btn-group pull-right">
              <a href="{% url 'products:create_product' %}" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-file visible-xs"></i><span class="hidden-xs">Create</span></a>
              <a href="{% url 'products:edit_product' pk=instance.pk %}" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-pencil visible-xs"></i><span class="hidden-xs">Edit</span></a>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirm-delete" ><i class="glyphicon glyphicon-trash visible-xs"></i><span class="hidden-xs">Delete</span></button>
        </div>
        {% endif %}
        
    </div>
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content alert alert-danger">
            <div class="modal-body">
                Are You Sure ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a href="{% url 'products:delete_product' pk=instance.pk %}" class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}

	{% if message %}
        <div class="alert alert-success alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{message}}
        </div>
    {% endif %}

    <div class="card">
    	<div class="card-header">
	        <h3>Basic Info<small></small></h2>
	 	</div>
	 	<div class="card-body">
	    	<table class="table table-striped" >
	    		<tr>
	    			<td>Name</td>
	    			<td>{{instance.name}}</td>
	    		</tr>
	    		<tr>
	    			<td>HSN Code</td>
	    			<td>{{instance.hsn_code}}</td>
	    		</tr>
	    		<tr>
	    			<td>Unit Sales Price</td>
	    			<td>{{instance.unit_price}}</td>
	    		</tr>
	    		<tr>
	    			<td>Input GST(%)</td>
	    			<td>{{instance.input_gst}}</td>
	    		</tr>
	    		<tr>
	    			<td>Output GST(%)</td>
	    			<td>{{instance.output_gst}}</td>
	    		</tr>
	    		{% if current_user_profile.tax_only == False %}
	    		<tr>
	    			<td>Untaxed</td>
	    			<td>{{instance.untaxed|yesno:"Yes,No"}}</td>
	    		</tr>
	    		{% endif %}
	    		<tr>
	    			<td>Stock</td>
	    			<td>{{instance.stock}}</td>
	    		</tr>
	    	</table>
    	</div>
    </div>
    <div class="card">
	    <div class="card-header">
	        <h3>Created &amp; Updated <small></small></h3>
	    </div>
	    <div class="card-body">
		    <table class="table table-striped">
			    	<tr>
		    			<td>Created</td>
		    			<td>{{instance.date_added|date:'d-m-y'}}</td>
		    		</tr>
		    		<tr>
		    			<td>Updated</td>
		    			<td>{{instance.date_updated|date:'d-m-y'|default:"-"}}</td>
		    		</tr>
		    </table>
	    </div>
	</div>
	<div class="card">
	    <div class="card-header">
	        <h3>Creator &amp; Updater <small></small></h3>
	    </div>
	    <div class="card-body">
		    <table class="table table-striped">
			    	<tr>
		    			<td>Creator</td>
		    			<td>{{instance.creator}}</td>
		    		</tr>
		    		<tr>
		    			<td>Updater</td>
		    			<td>{{instance.updater|default:"-"}}</td>
		    		</tr>
		    </table>
	    </div>
	</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}
                    

templates/products/view_products.html
{% extends "base.html" %}
{% load i18n %}


{% block headerbar %}
    <div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
         <div class="btn-group pull-right">
            {% if admin %}
              <a href="{% url 'products:create_product' %}" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-file visible-xs"></i><span class="hidden-xs">Create</span></a>
            {% endif %}

              <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter"><i class="glyphicon glyphicon-filter visible-xs"></i><span class="hidden-xs">Filter</span></button>
        </div>
    </div>
{% endblock %}

{% block filter %}
    <div id="filter" class="col-sm-3 col-md-2 collapse width">
        <div class="filter-content">
            <form action="{% url 'products:view_products' %}">
                <div class="row">
                    <label class="col-xs-12" for="filter_q">Query</label>
                    <input id="filter_q" type="text" name="q" placeholder="Enter Query..."/>
                </div>
                <section class="submitContainer">
                    <input type="submit" value="Filter" class="btn btn-primary" />
                </section>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}

    {% if message %}
        <div class="alert alert-success alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{message}}
        </div>
    {% endif %}

    <div class="card">
                
        {% if instances %}
            
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>HSN Code</th>
                            <th>Unit Price</th>
                            <th>Input GST(%)</th>
                            <th>Output GST(%)</th>
                            <th>Stock</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in instances %}
                        <tr class="check_items_row">
                            <td><a href="{% url 'products:view_product' pk=instance.pk %}">{{instance.name}}</a></td>
                            <td>{{instance.hsn_code|default:"-"}}</td>
                            <td>{{instance.unit_price}}</td>
                            <td>{{instance.input_gst|default:"-"}}</td>
                            <td>{{instance.output_gst|default:"-"}}</td>
                            <td>{{instance.stock}}</td>
                      
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if instances.has_previous %}
                        <a href="?page={{ instances.previous_page_number }}{% if query %}&q={{query}}{% endif %}" class="glyphicon glyphicon-chevron-left">&nbsp;</a>
                    {% endif %}

                    <span class="current">
                        Page {{ instances.number }} of {{ instances.paginator.num_pages }}.
                    </span>

                    {% if instances.has_next %}
                        <a href="?page={{ instances.next_page_number }}{% if query %}&q={{query}}{% endif %}" class="glyphicon glyphicon-chevron-right">&nbsp;</a>
                    {% endif %}
                </span>
            </div>     
        {% else %}
            {% include 'includes/not_found.html' %}
        {% endif %}                       
    </div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}