app/urls.py
from django.conf.urls import url
import views


urlpatterns=[
	url(r'^$',views.dashboard,name="dashboard"),
	url(r'^view-notifications/$',views.view_notifications,name='view_notifications'),
	url(r'^mark-as-read/(?P<pk>.*)/$',views.mark_as_read,name='mark_as_read'),
	url(r'^mark-as-not-read/(?P<pk>.*)/$',views.mark_as_not_read,name='mark_as_not_read'),
	url(r'^search-result/$',views.search_result,name='search_result'),
	url(r'^mark-as-deleted/(?P<pk>.*)/$',views.mark_as_deleted,name='mark_as_deleted'),
]

offroad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls import (
handler400, handler403, handler404, handler500
)


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^',include('app.urls',namespace='dashboard')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^shops/',include('shops.urls',namespace='shops')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^customers/',include('customers.urls',namespace='customers')),
    url(r'^purchases/',include('purchases.urls',namespace='purchases')),
    url(r'^vendors/',include('vendors.urls',namespace='vendors')),
    url(r'^sales/',include('sales.urls',namespace='sales')),
    url(r'^reports/',include('reports.urls',namespace='reports')),
    url(r'^app/',include('app.urls',namespace='app')),
    url(r'^expense/',include('expense.urls',namespace='expense')),
    url(r'^cheque-details/',include('cheques.urls',namespace='cheques')),
    
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT,}),
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT,}),
]

handler400 = "app.views.handler400"
handler403 = "app.views.handler403"
handler404 = "app.views.handler404"
handler500 = "app.views.handler500"

purchases/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views


urlpatterns = [
    url(r'^create-purchase/$', views.create_purchase, name='create_purchase'),
    url(r'^view-purchase/(?P<pk>.*)/$', views.view_purchase, name='view_purchase'),
    url(r'^edit-purchase/(?P<pk>.*)/$', views.edit_purchase, name='edit_purchase'),
    url(r'^purchases/$', views.view_purchases, name='view_purchases'),
    url(r'^delete-purchase/(?P<pk>.*)/$', views.delete_purchase, name='delete_purchase'),

    url(r'^get-input-tax/$', views.get_input_tax, name='get_input_tax'),
       
]

vendors/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from vendors.autocomplete_light_registry import VendorAutocomplete


urlpatterns = [
    url(r'^create-vendor/$', views.create_vendor, name='create_vendor'),
    url(r'^view-vendor/(?P<pk>.*)/$', views.view_vendor, name='view_vendor'),
    url(r'^edit-vendor/(?P<pk>.*)/$', views.edit_vendor, name='edit_vendor'),
    url(r'^view-vendors/$', views.view_vendors, name='view_vendors'),  
    url(r'^delete-vendor/(?P<pk>.*)/$', views.delete_vendor, name='delete_vendor'),
    url(r'^vendor-autocomplete/$',VendorAutocomplete.as_view(), name='vendor-autocomplete',),
    url(r'^create-vendor-popup/$', views.create_vendor_popup, name='create_vendor_popup'),
]

purchases/models.py
from __future__ import unicode_literals
from django.db import models
from app.models import BaseModel
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.utils import timezone


class Purchase(BaseModel):
    shop = models.ForeignKey('shops.Shop',limit_choices_to={"is_deleted":False})
    purchase_id = models.CharField(max_length=128)
    date = models.DateTimeField(default=timezone.now)
    vendor = models.ForeignKey('vendors.Vendor',limit_choices_to={"is_deleted":False},blank=True,null=True)
    purchase_date = models.DateTimeField(blank=True,null=True)
    invoice_no = models.CharField(max_length=120,blank=True,null=True)
    other_charges = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,blank=True,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    final_total = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,blank=True,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    paid = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,blank=True,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    balance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,blank=True,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    purchase_type = models.CharField(max_length=128,choices=(('intra_state','Intra State'),('inter_state','Inter State')),default='intra_state')
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'purchase'
        verbose_name = _('purchase')
        verbose_name_plural = _('purchases')
        ordering = ('-date',)
    
    class Admin:
        list_display = ('-date',)

    def __unicode__(self):
        return str(self.purchase_id)


class PurchaseProduct(models.Model):
    purchase = models.ForeignKey('purchases.Purchase',limit_choices_to={"is_deleted":False})
    product = models.ForeignKey('products.Product',limit_choices_to={"is_deleted":False})
    unit_cost = models.DecimalField(decimal_places=2, max_digits=15,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    input_gst = models.DecimalField(decimal_places=2, max_digits=15,blank=True,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    quantity = models.PositiveIntegerField()
    offer = models.DecimalField(decimal_places=2, max_digits=15,blank=True,null=True,validators=[MinValueValidator(Decimal('0.00'))])
    tax_amount = models.DecimalField(default=0.0,decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    amount = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,null=True, validators=[MinValueValidator(Decimal('0.00'))])
    total_amount = models.DecimalField(default=0.0,decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'purchase_product'
        verbose_name = _('purchase product')
        verbose_name_plural = _('purchase products')
        ordering = ('purchase','id',)
    
    class Admin:
        list_display = ('purchase',)

    def __unicode__(self):
        return str(self.purchase)      

purchases/views.py
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
import json
from django.shortcuts import render, get_object_or_404
import datetime
from django.db.models import Q
from purchases.models import Purchase, PurchaseProduct
from app.functions import get_current_shop, generate_form_errors
from django.forms.formsets import formset_factory
from purchases.forms import PurchaseProductForm, PurchaseForm
from products.models import Product
from vendors.models import Vendor
from vendors.forms import VendorForm
from django.contrib.auth.decorators import login_required
from app.decorators import check_group
from django.forms.models import inlineformset_factory
from django.forms.widgets import Select, TextInput
from purchases.functions import remove_previous_product_stock
from dal import autocomplete
from django.db.models import Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import re
from users.models import Profile
from decimal import Decimal
from django.utils.translation import ugettext_lazy as _


@login_required
@check_group(['admin'])
def create_purchase(request):  
    PurchaseProductFormset = formset_factory(PurchaseProductForm,min_num=1,validate_min=True,extra=0)
    current_shop = get_current_shop(request)
    vendor_form = VendorForm()

    if request.method == "POST":
        form = PurchaseForm(request.POST)

        purchase_product_formset = PurchaseProductFormset(request.POST,prefix='purchase_product_formset')
        for field in purchase_product_formset:
            field.fields['product'].queryset = Product.objects.filter(shop=current_shop,is_deleted=False)
        
        if form.is_valid() and purchase_product_formset.is_valid(): 
            
            purchase_id = 'P1'
            purchase_obj = Purchase.objects.filter(shop=current_shop).order_by("-date_added")[:1]
            if purchase_obj:
                for purchase in purchase_obj:
                    purchase_id = 'P'+str(int(re.findall(r'\d+', purchase.purchase_id)[0]) + 1)
            
            balance = form.cleaned_data['balance'] 
            vendor = form.cleaned_data['vendor']

            #create purchase
            data = form.save(commit=False)
            data.creator = request.user
            data.updater = request.user
            data.purchase_id = purchase_id
            data.shop = current_shop
            data.date_added = datetime.datetime.now()
            data.save()

            #save PurchaseProduct
            for form in purchase_product_formset:
                product = form.cleaned_data['product']
                unit_cost = form.cleaned_data['unit_cost']
                input_gst = form.cleaned_data['input_gst']
                quantity = form.cleaned_data['quantity']
                offer = form.cleaned_data['offer']
                tax_amount = form.cleaned_data['tax_amount']
                amount = form.cleaned_data['amount']
                total_amount = form.cleaned_data['total_amount']

                PurchaseProduct(      
                    product = product,
                    purchase = data,
                    unit_cost = unit_cost,
                    input_gst = input_gst,
                    quantity = quantity,
                    offer = offer,
                    tax_amount =tax_amount,
                    amount = amount,
                    total_amount = total_amount
                ).save()

                if Product.objects.filter(pk=product.pk,shop=current_shop).exists():
                        current_stock =  Product.objects.get(pk=product.pk,shop=current_shop).stock
                        Product.objects.filter(pk=product.pk,shop=current_shop).update(stock=quantity + current_stock)
            
            #update balance of vendor
            if vendor:
                current_balance =  Vendor.objects.get(pk=vendor.pk,shop=current_shop,is_deleted=False).balance
                Vendor.objects.filter(pk=vendor.pk,shop=current_shop,is_deleted=False).update(balance= current_balance + balance)

            request.session['message'] = 'Form Submitted successfully'
            return HttpResponseRedirect(reverse('purchases:view_purchase', kwargs = {'pk' : data.pk}))

        else:
            errors =generate_form_errors(form,formset=False)
            errors +=generate_form_errors(purchase_product_formset,formset=True)
            context = {
                "form" : form,
                "vendor_form" : vendor_form,
                "title" : "Create Purchase",
                "purchase_product_formset" : purchase_product_formset,
                "errors" : errors,
                "purchases_active":"active"
            }          
            
        return render(request, 'purchases/entry_purchase.html', context)       

    else: 
        form = PurchaseForm()
        
        purchase_product_formset = PurchaseProductFormset(prefix='purchase_product_formset')
        for field in purchase_product_formset:
            field.fields['product'].queryset = Product.objects.filter(shop=current_shop,is_deleted=False)
        
        context = {
            "form" : form,
            "vendor_form" : vendor_form,
            "purchase_product_formset" : purchase_product_formset,
            "title" : "Create Purchase",
            "url" : reverse('purchases:create_purchase'),
            "purchases_active":"active"
        }
        return render(request, 'purchases/entry_purchase.html', context)
    


@login_required
@check_group(['admin'])
def edit_purchase(request,pk):
    current_shop = get_current_shop(request)
    purchase_instance = get_object_or_404(Purchase.objects.filter(pk=pk,is_deleted=False,shop=current_shop))
    vendor_form = VendorForm()

    PurchaseProductFormset = inlineformset_factory(
                                              Purchase,
                                              PurchaseProduct, 
                                              can_delete=True,
                                              extra=0,
                                              min_num=1,
                                              validate_min=True,
                                              exclude=('shop','purchase'),
                                              widgets = {
                                                    'product': autocomplete.ModelSelect2(url='products:product-autocomplete',attrs={'data-placeholder': 'Select Product','data-minimum-input-length': 1}),
                                                    'quantity' : TextInput(attrs={'placeholder': 'Enter quantity','class':'required form-control'}),
                                                    'unit_cost' : TextInput(attrs={'placeholder': 'Enter unit cost(inc. tax)','label': 'Unit cost','class':'required form-control'}),
                                                    'input_gst' : TextInput(attrs={'placeholder': 'Input Tax','class': 'required form-control'}),
                                                    'offer' : TextInput(attrs={'placeholder': 'Enter offer','class':'required form-control'}),
                                                    'amount' : TextInput(attrs={'placeholder': 'Enter amount','class':'required form-control'}),
                                                    'tax_amount' : TextInput(attrs={'placeholder': 'Tax amount','class':'required form-control'}),
                                                    'total_amount' : TextInput(attrs={'placeholder': 'Enter total amount','class':'required form-control'}),
                                                },
                                              error_messages={
                                                'product': {
                                                    'required': _("product field is required."),
                                                },
                                                'unit_cost': {
                                                    'required': _("Unit Cost field is required."),
                                                },
                                                'quantity': {
                                                    'required': _("Quantity field is required."),
                                                },
                                              }
                                            )
    
    if request.method == "POST":
        response_data = {}  
        form = PurchaseForm(request.POST,instance=purchase_instance)
        purchase_product_formset = PurchaseProductFormset(request.POST,prefix='purchase_product_formset',instance=purchase_instance)
        
        error = ''
        
        # checking quantity and stock  of deleted product to ensure quantity is less than stock
        if purchase_product_formset.deleted_forms:
            for deleted_form in purchase_product_formset.deleted_forms:
                if deleted_form.instance.product.stock <= deleted_form.instance.quantity:
                    error = "Invalid operation, Product can not removed because of incorrect quantity"

        #tacking vendor and vendor balance in variables
        vendor_balance = purchase_instance.balance
        vendor = purchase_instance.vendor

        if form.is_valid() and purchase_product_formset.is_valid():

            #remove previous  Purchase Product
            purchase_product = PurchaseProduct.objects.filter(purchase=purchase_instance.pk,is_deleted=False)
            for purchase_product_form in purchase_product_formset:
                new_product = purchase_product_form.cleaned_data['product']
                new_quantity = purchase_product_form.cleaned_data['quantity']

templates/purchases/entry_purchase.html
{% extends "base.html" %}
{% load i18n %}

{% block headerbar %}
	<div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
    </div>
{% endblock %}

{% block content %}

	{% if errors %}
		<div class="alert alert-danger">
		  <strong>Error!</strong> 
		    {{errors | safe}}
		</div>
	{% endif %}
	{% include 'includes/create_product_popup.html' %}
	{% include 'includes/create_vendor_popup.html' %}

	<form action="{{ url }}" method="post" class="form-horizontal">
		{% csrf_token %}

		<div class="form-group {% if form.date.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.date.label.id_for_label}}" class="col-sm-5 control-label">{{form.date.label}}</label>
            <div class="col-sm-5">
                <div class="fg-line">
                    {{form.date}}
                </div>
            </div>
        </div>
        <div class="form-group {% if form.vendor.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.vendor.label.id_for_label}}" class="col-sm-5 control-label">{{form.vendor.label}} <a href="#" data-toggle="modal" data-target="#create-vendor"><span class="glyphicon glyphicon-plus"></span></a></label>
            <div class="col-xs-12 col-sm-7">
                <div class="fg-line">
                    {{form.vendor}}
                </div>
            </div>
        </div>
		<div class="clearfix"></div>
		<div class="form-group {% if form.purchase_date.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.purchase_date.label.id_for_label}}" class="col-sm-5 control-label">{{form.purchase_date.label}}</label>
            <div class="col-sm-5">
                <div class="fg-line">
                    {{form.purchase_date}}
                </div>
            </div>
        </div>
        <div class="form-group {% if form.purchase_type.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.purchase_type.label.id_for_label}}" class="control-label col-sm-5">{{form.purchase_type.label}}</label>
            <div class="col-sm-7">
                <div class="fg-line">
                    {{form.purchase_type}}
                </div>
            </div>
        </div>
        <div class="form-group {% if form.invoice_no.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.invoice_no.label.id_for_label}}" class="col-sm-5 control-label">{{form.invoice_no.label}}</label>
            <div class="col-sm-5">
                <div class="fg-line">
                    {{form.invoice_no}}
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

		<section class="innerBox">
				<h3>Purchased Item</h3>
				<div class="purchase_product_formset table-responsive">			        
					<table class="table">
						<thead>
							<tr>
								<th>SL.No</th>
								<th>Product <a href="#" data-toggle="modal" data-target="#create-product"><span class="glyphicon glyphicon-plus"></span></a></th>
								<th>Unit Price</th>
								<th>GST(%)</th>
								<th>Quantity</th>
								<th>Discount</th>
								<th>Net Amount</th>
								<th>GST Amount</th>
								<th>Total</th>
								<th></th>
							</tr>	
						</thead>
						<tbody>
							{% for form in purchase_product_formset.forms %}			    
							<tr class="{% if form.instance.product.untaxed == True and current_user_profile.tax_only == True %}hidden{% else %}countable{% endif %} form_set_row">
								<td class="sl_no"></td>
								<td>
									{{ form.id }}
									<span class="purchase_product_product">									
										{{ form.product }}
									</span>
								</td>
								<td>
									<span class="purchase_product_unit_cost">
										{{ form.unit_cost}}
									</span>
								</td>
								<td>
									<span class="purchase_product_input_tax">
										{{ form.input_gst}}
									</span>
								</td>
								<td>
									<span class="purchase_product_quantity">
										{{ form.quantity }}
									</span>
								</td>
								<td>
									<span class="purchase_product_offer">
										{{ form.offer}}
									</span>
								</td>
								<td>
									<span class="purchase_product_amount">
										{{ form.amount }}
									</span>
								</td>
								<td>
									<span class="purchase_product_tax_amount">
										{{ form.tax_amount }}
									</span>
								</td>
								<td>
									<span class="purchase_product_total_amount">
										{{ form.total_amount }}
									</span>
								</td>
								<td class="fm-remove">{% if purchase_product_formset.can_delete %}{{ form.DELETE }}{% endif %}</td>
							</tr>
							{% endfor %}
						</tbody>
						<tfoot>
							<tr>
								<th colspan="5">Total</th>
								<td class="total_discount">
									<input class="form-control" id="id_total_discount" name="total_discount" placeholder="Total Discount" type="text" value="0.0" required />
								</td>
								<td class="total_net_amount">
					                <input class="required form-control" id="id_total_net_amount" name="total_net_amount" placeholder="Total Net Amount" type="text" value="" />
								</td>
								<td class="total_tax_amount">
									<input class="required form-control" id="id_total_tax_amount" name="total_tax_amount" placeholder="Total Tax Amount" type="text" value="0.0" required />
								</td>
								<td class="total">
									 <input class="required form-control" id="id_total" name="total" placeholder="Total" type="text" value="0.0" required />
								</td>
							</tr>
						</tfoot>						
					</table>
					{{ purchase_product_formset.management_form }}
				</div>
			</section>

        <div class="clearfix"></div>
        <div class="form-group {% if form.other_charges.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.other_charges.label.id_for_label}}" class="col-sm-4 control-label">{{form.other_charges.label}}</label>
            <div class="col-sm-8">
                <div class="fg-line">
                    {{form.other_charges}}
                </div>
            </div>
        </div>
        <div class="form-group {% if form.final_total.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.final_total.label.id_for_label}}" class="col-sm-4 control-label">Total</label>
            <div class="col-sm-8">
                <div class="fg-line">
                    {{form.final_total}}
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="form-group {% if form.paid.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.paid.label.id_for_label}}" class="col-sm-4 control-label">{{form.paid.label}}</label>
            <div class="col-sm-8">
                <div class="fg-line paid">
                    {{form.paid}}
                </div>
            </div>
        </div>
        <div class="form-group {% if form.balance.errors %} has-error {% endif %} col-sm-6">
            <label for="{{form.balance.label.id_for_label}}" class="col-sm-4 control-label">{{form.balance.label}}</label>
            <div class="col-sm-8">
                <div class="fg-line balance">
                    {{form.balance}}
                </div>
            </div>
        </div>
		<div class="form-group"> 
		    <div class="col-sm-offset-2 col-sm-10">
		      <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		  </div>
	</form>				
{% endblock %}

{% block static %}
	{% load static %}
	<link href="{% static 'css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
	<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}" charset="UTF-8"></script>
	<script type="text/javascript">
	    $('#id_date,#id_purchase_date').datetimepicker({
	       	format: "dd-mm-yyyy",
	        weekStart: 1,
	        todayBtn:  1,
			autoclose: 1,
			todayHighlight: 1,
			startView: 2,
			forceParse: 0,
			minView : 2
	    });
	</script>
	<script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
	<script>
		$(document).ready(function(){	
			$('.purchase_product_formset table tr.form_set_row').formset({
	            prefix: '{{ purchase_product_formset.prefix }}',
	            formCssClass: 'dynamic-formset1'
	        });
	        $('.dynamic-formset1-add .add-row.icon_add_item').click(function(){
	        	$('.purchase_product_formset table tr.form_set_row:last').removeClass('hidden');
	        	$('.purchase_product_formset table tr.form_set_row:last').addClass('countable');
	        });
			function calculate(){
				var total_net_amount = 0;
	        	var total_tax_amount = 0;
				var total = 0; 
				var balance = 0;   
				var total_discount =0;  		
				
				$('.purchase_product_formset table tr[style!="display: none;"].form_set_row.countable').each(function(index){
					$this = $(this);
					$this.find('.sl_no').html(index+1);
					var quantity = parseFloat($this.find('.purchase_product_quantity input').val());
					if(!quantity){
						quantity = 0;
					}
					var unit_cost = parseFloat($this.find('.purchase_product_unit_cost input').val());
					if(!unit_cost){
						unit_cost = 0;
					}
					var input_tax = parseFloat($this.find('.purchase_product_input_tax input').val());
					if(!input_tax){
						input_tax = 0;
					}
					var offer = parseFloat($this.find('.purchase_product_offer input').val());
					if(!offer){
						offer = 0;
					}
					var net_amount = quantity * unit_cost - offer;
					$this.find('.purchase_product_amount input').val(net_amount.toFixed(2));

					var tax_amount = net_amount*(input_tax/100);
					$this.find('.purchase_product_tax_amount input').val(tax_amount.toFixed(2));

					var total_amount = net_amount + tax_amount
					$this.find('.purchase_product_total_amount input').val(total_amount.toFixed(2));

					total_discount += offer
					total_net_amount += net_amount;
					total_tax_amount += tax_amount;
					total += total_amount;
				});
				
				$('.total_discount input').val(total_discount.toFixed(2));
				$('.total_net_amount input').val(total_net_amount.toFixed(2));
				$('.total_tax_amount input').val(total_tax_amount.toFixed(2));
				$('.total input').val(total.toFixed(2));

				var other_charges =  parseFloat($('#id_other_charges').val());
				if(!other_charges){
					other_charges = 0;
				}
				var final_total = total + other_charges;
				$('#id_final_total').val(final_total.toFixed(2));

				var paid = parseFloat($('.paid input').val());
				if(!paid){
						paid = 0;
					}
				balance = final_total - paid
				$('.balance input').val(balance.toFixed(2));
			}
	        
	        calculate();

	       	function getInputTax($selector){
	        	var $this = $selector;		
	        	var url = "{% url 'purchases:get_input_tax' %}";
	        	var id = $this.val();
	        	var $parent = $this.parents('tr.form_set_row');
	        	if(id != '' && id != null){
		        	$.ajax({
		        		type : "GET",
						url : url,
						dataType : 'json',
						data : {
							id : id,
						},
						success : function(data) {
							var status = data['status'];
							var input_tax = data['input_tax']
							
							if (status == "true"){
								$parent.find('.purchase_product_input_tax input').val(input_tax);
								
								calculate();	
								
							}								
						},
		        	});	        		
	        	}
	        }
	        $(document).on('change','span.purchase_product_product select',function(){
	        	$selector = $(this);
	        	getInputTax($selector);
	        });
	        setInterval(function(){
	        	calculate();
	        },100);
	        $('input[type=text]').focus(function () { 
                $(this).select();
            });
        });
	</script>
	{{form.media}}
	{{f.media}}
{% endblock %}