app/urls.py
from django.conf.urls import url
import views


urlpatterns=[
	url(r'^$',views.dashboard,name="dashboard"),
	url(r'^view-notifications/$',views.view_notifications,name='view_notifications'),
	url(r'^mark-as-read/(?P<pk>.*)/$',views.mark_as_read,name='mark_as_read'),
	url(r'^mark-as-not-read/(?P<pk>.*)/$',views.mark_as_not_read,name='mark_as_not_read'),
	url(r'^search-result/$',views.search_result,name='search_result'),
	url(r'^mark-as-deleted/(?P<pk>.*)/$',views.mark_as_deleted,name='mark_as_deleted'),
]

cheques/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from django.views import generic


urlpatterns = [               
    
    url(r'^create-cheque-details/$',views.create_cheque,name='create_cheque'),
    url(r'^view-cheques-details/$',views.view_cheques,name='view_cheques'),
    url(r'^edit-cheque-details/(?P<pk>.*)/$',views.edit_cheque,name='edit_cheque'),
    url(r'^view-cheque-details/(?P<pk>.*)/$',views.view_cheque,name='view_cheque'),
    url(r'^delete-cheque-details/(?P<pk>.*)/$',views.delete_cheque,name='delete_cheque'),
]

offroad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls import (
handler400, handler403, handler404, handler500
)


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^',include('app.urls',namespace='dashboard')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^shops/',include('shops.urls',namespace='shops')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^customers/',include('customers.urls',namespace='customers')),
    url(r'^purchases/',include('purchases.urls',namespace='purchases')),
    url(r'^vendors/',include('vendors.urls',namespace='vendors')),
    url(r'^sales/',include('sales.urls',namespace='sales')),
    url(r'^reports/',include('reports.urls',namespace='reports')),
    url(r'^app/',include('app.urls',namespace='app')),
    url(r'^expense/',include('expense.urls',namespace='expense')),
    url(r'^cheque-details/',include('cheques.urls',namespace='cheques')),
    
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT,}),
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT,}),
]

handler400 = "app.views.handler400"
handler403 = "app.views.handler403"
handler404 = "app.views.handler404"
handler500 = "app.views.handler500"

vendors/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from vendors.autocomplete_light_registry import VendorAutocomplete


urlpatterns = [
    url(r'^create-vendor/$', views.create_vendor, name='create_vendor'),
    url(r'^view-vendor/(?P<pk>.*)/$', views.view_vendor, name='view_vendor'),
    url(r'^edit-vendor/(?P<pk>.*)/$', views.edit_vendor, name='edit_vendor'),
    url(r'^view-vendors/$', views.view_vendors, name='view_vendors'),  
    url(r'^delete-vendor/(?P<pk>.*)/$', views.delete_vendor, name='delete_vendor'),
    url(r'^vendor-autocomplete/$',VendorAutocomplete.as_view(), name='vendor-autocomplete',),
    url(r'^create-vendor-popup/$', views.create_vendor_popup, name='create_vendor_popup'),
]

cheques/models.py
from django.db import models
from app.models import BaseModel
from decimal import Decimal
from django.utils.translation import ugettext_lazy as _

class Cheque(BaseModel):
    shop = models.ForeignKey('shops.Shop',limit_choices_to={"is_deleted":False})
    date = models.DateTimeField()
    vendor = models.ForeignKey('vendors.Vendor',limit_choices_to={"is_deleted":False},blank=True,null=True)
    cheque_number = models.CharField(max_length=128,null=True,blank=True)
    name = models.CharField(max_length=128)
    account_number = models.CharField(max_length=128,null=True,blank=True)
    amount = models.DecimalField(default=0,decimal_places=2,max_digits=15)
    details = models.TextField(max_length=256,null=True,blank=True)
    
    is_notified = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
     
    class Meta:
        db_table = 'cheque'
        verbose_name = _('cheque')
        verbose_name_plural = _('cheques')
        ordering = ('-date',)        
  
    def __unicode__(self):
        return self.name

cheques/forms.py
from django import forms
from cheques.models import Cheque
from django.forms.widgets import TextInput, Select,Textarea, DateTimeInput
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete


class ChequeForm(forms.ModelForm):
    
    class Meta:
        model = Cheque
        exclude = ['creator','updater','is_deleted','date_added','date_updated','shop','is_notified']
        widgets = {
            'date' : DateTimeInput(attrs={'placeholder': '*Enter date','class':'required form-control'}),
            'vendor': autocomplete.ModelSelect2(url='vendors:vendor-autocomplete',attrs={'data-placeholder': 'Select Vendor','data-minimum-input-length': 1}),
            'cheque_number' : TextInput(attrs={'placeholder': 'Cheque Number','class':'required form-control'}),
            'name' : TextInput(attrs={'placeholder': '*Name','class':'required form-control'}),
            'account_number' : TextInput(attrs={'placeholder': 'Account Number','class':'required form-control'}),
            'amount' : TextInput(attrs={'placeholder': '*Amount','class':'required form-control'}),
            'details': Textarea(attrs={'class': 'form-control','placeholder' : 'Details'}),
        }
        error_messages = {
            'date' : {
                'required' : _("Date field is required."),
            },
            'name' : {
                'required' : _("Name field is required."),
            },
            'amount' : {
                'required' : _("Amount field is required."),
            },
                                      
        }
        labels ={
            'date' :'Processing date'
        }

cheques/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponse, HttpResponseRedirect
import json
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.contrib.auth.models import User
from cheques.forms import ChequeForm
from cheques.models import Cheque
from app.functions import get_current_shop, generate_form_errors
from django.contrib.auth.decorators import login_required
from app.decorators import check_group
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
@check_group(['admin'])
def create_cheque(request):
    if request.method == "POST":
        form = ChequeForm(request.POST)
            
        if form.is_valid():

            #get current shop
            shop = get_current_shop(request) 

            #create cheque
            data = form.save(commit=False)
            data.creator = request.user
            data.updater = request.user
            data.shop = shop
            data.save()
            
            request.session['message'] = 'Form Submitted successfully'
            return HttpResponseRedirect(reverse('cheques:view_cheque', kwargs = {'pk' : data.pk}))
        
        else:    
            errors =generate_form_errors(form,formset=False)   
            context = {
	            "form" : form,
	            "title" : "Error",
                "errors":errors,
                "cheques_active":"active"
	            
	        }          
            
        return render(request, 'cheques/entry_cheque.html', context)

    else: 
        form = ChequeForm()
        
        context = {
            "form" : form,
            "title" : "Create Cheque",
            "url" : reverse('cheques:create_cheque'),
            "redirect" : True,
            "cheques_active":"active"
            
        }
        return render(request, 'cheques/entry_cheque.html', context)
    
    
@login_required
@check_group(['admin'])
def edit_cheque(request,pk):
    instance = get_object_or_404(Cheque.objects.filter(pk=pk,is_deleted=False))
    
    if request.method == "POST":
        response_data = {}  
        form = ChequeForm(request.POST,instance=instance)
        
        if form.is_valid(): 
            
            #update cheque
            data = form.save(commit=False)
            data.updater = request.user
            data.date_updated = datetime.datetime.now()
            data.save()
            
            request.session['message'] = 'Form Edited successfully'
            return HttpResponseRedirect(reverse('cheques:view_cheque', kwargs = {'pk' : data.pk}))
        else:
            errors =generate_form_errors(form,formset=False)
            context = {
                "form" : form,
                "title" : "Update Cheque",
                "cheques_active":"active"
            }          
            
        return render(request, 'cheques/entry_cheque.html', context)

    else: 
        form = ChequeForm(instance=instance)
        
        context = {
            "form" : form,
            "title" : "Edit cheque : " + instance.name,
            "instance" : instance,
            "cheques_active":"active"
        }
        return render(request, 'cheques/entry_cheque.html', context)

       
@login_required
@check_group(['admin'])
def view_cheques(request):
    current_shop = get_current_shop(request)
    instances = Cheque.objects.filter(shop=current_shop,is_deleted=False)

    try:
        message = request.session['message']
        del request.session['message']
    except KeyError:
        message = None

    title = "Cheques"


    #filter by query
    query = request.GET.get("q")
    if query:
        title = "Cheques (%s)" % query
        try:
            date_query = datetime.datetime.strptime(query,"%d-%m-%y")
        except:
            date_query = query
        instances = instances.filter(Q(name__icontains=query)|Q(date__icontains=date_query))

    #code for page nation starts here
    paginator = Paginator(instances, 100)
    page = request.GET.get('page')

    try:
        instances = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        instances = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        instances = paginator.page(paginator.num_pages)
        
    context = {
        'title' : title,
        "instances" : instances,
        'query':query,
        "message" : message,
        "cheques_active":"active" 
    }
    return render(request,'cheques/view_cheques.html',context) 


@login_required
@check_group(['admin'])
def view_cheque(request,pk):
    instance = get_object_or_404(Cheque.objects.filter(pk=pk,is_deleted=False))
    
    try:
        message = request.session['message']
        del request.session['message']
    except KeyError:
        message = None

    context = {
        "instance" : instance,
        "title" : "Cheque : " + str(instance.name),
        "message" : message,
        "cheques_active":"active"
    }
    return render(request,'cheques/view_cheque.html',context)


@login_required
@check_group(['admin'])
def delete_cheque(request,pk):
    instance = get_object_or_404(Cheque.objects.filter(pk=pk))
    Cheque.objects.filter(pk=pk).update(is_deleted=True)
    
    request.session['message'] = 'Successfully Deleted'
    return HttpResponseRedirect(reverse('cheques:view_cheques'))


@login_required
@check_group(['admin'])
def create_cheque_popup(request): 

    if request.method == "POST":
        #get current shop
        shop = get_current_shop(request) 
        form = ChequeForm(request.POST,request=request)
            
        if form.is_valid():

            #create cheque_id
            cheque_id = 1
            cheque_obj = Cheque.objects.filter(shop=shop).order_by("-date_added")[:1]
            if cheque_obj:
                for cheque in cheque_obj:
                    cheque_id = cheque.cheque_id + 1
            

            #create farmer
            data = form.save(commit=False)
            data.creator = request.user
            data.updater = request.user
            data.cheque_id = cheque_id
            data.shop = shop
            data.save()
            
            response_data ={
                'status':'true',
                'message': "Cheque %s Created Successfully" %(data.name),
            }
            
            response = HttpResponse(json.dumps(response_data), content_type='application/javascript')
            return response
        
        else:    
            errors =generate_form_errors(form,formset=False)   
            response_data = {
                'status':'false',
                'message': errors,
            }
            response = HttpResponse(json.dumps(response_data), content_type='application/javascript')  
            return response

templates/cheques/entry_cheque.html
{% extends "base.html" %}
{% load i18n %}

{% block headerbar %}
	<div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
    </div>
{% endblock %}

{% block content %}
	{% if errors %}
		<div class="alert alert-danger">
		  <strong>Error!</strong> 
		    {{errors | safe}}
		</div>
	{% endif %}
	
	<form action="{{ url }}" method="post" class="form-horizontal">
		{% csrf_token %}
		{% for field in form %}
		  <div class="form-group {% if field.errors %} has-error {% endif %}">
		    <label class="control-label col-sm-2" for="{{field.id_for_label}}">{{field.label}} :</label>
		    <div class="col-sm-8">
		      {{field}}
		    </div>
		  </div>
		  {% if field.help_text %}
	        <p class="help">{{ field.help_text|safe }}</p>
	      {% endif %}
		{% endfor %}
		
		<div class="form-group"> 
		    <div class="col-sm-offset-2 col-sm-10">
		    	<button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
	</form>
{% endblock %}

{% block static %}
	{% load static %}
	<link href="{% static 'css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
	<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}" charset="UTF-8"></script>
	<script type="text/javascript">
	    $('#id_date,#id_purchase_date').datetimepicker({
	       	format: "dd-mm-yyyy",
	        weekStart: 1,
	        todayBtn:  1,
			autoclose: 1,
			todayHighlight: 1,
			startView: 2,
			forceParse: 0,
			minView : 2
	    });
	    $('input[type=text]').focus(function () { 
            $(this).select();
        });
	</script>
	{{form.media}}
{% endblock %}

templates/cheques/view_cheque.html
{% extends "base.html" %}
{% load i18n %}


{% block headerbar %}
	<div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-6 col-sm-4">{{title}}</h4>
         <div class="btn-group pull-right">
              <a href="{% url 'cheques:create_cheque' %}" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-file visible-xs"></i><span class="hidden-xs">Create</span></a>
              <a href="{% url 'cheques:edit_cheque' pk=instance.pk %}" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-pencil visible-xs"></i><span class="hidden-xs">Edit</span></a>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirm-delete" ><i class="glyphicon glyphicon-trash visible-xs"></i><span class="hidden-xs">Delete</span></button>
        </div>
    </div>
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content alert alert-danger">
            <div class="modal-body">
                Are You Sure ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a href="{% url 'cheques:delete_cheque' pk=instance.pk %}" class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

	{% if message %}
        <div class="alert alert-success alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{message}}
        </div>
    {% endif %}

    <div class="card">
    	<div class="card-header">
	        <h3>Basic Info<small></small></h2>
	 	</div>
	 	<div class="card-body">
	    	<table class="table table-striped" >
	    		<tr>
	    			<td>Date</td>
	    			<td>{{instance.date|date:'d-m-y'}}</td>
	    		</tr>
	    		<tr>
	    			<td>Vendor</td>
	    			<td>{{instance.vendor.name}}</td>
	    		</tr>
	    		<tr>
	    			<td>Name</td>
	    			<td>{{instance.name}}</td>
	    		</tr>
	    		<tr>
	    			<td>Cheque Number</td>
	    			<td>{{instance.cheque_number|default:"-"}}</td>
	    		</tr>
	    		<tr>
	    			<td>Account Number</td>
	    			<td>{{instance.account_number|default:"-"}}</td>
	    		</tr>
	    		<tr>
	    			<td>Amount</td>
	    			<td>{{instance.amount|default:"-"}}</td>
	    		</tr>
	    		<tr>
	    			<td>Details</td>
	    			<td>{{instance.details}}</td>
	    		</tr>
	    	</table>
    	</div>
    </div>
	<div class="card">
	    <div class="card-header">
	        <h3>Created &amp; Updated <small></small></h3>
	    </div>
	    <div class="card-body">
		    <table class="table table-striped">
			    	<tr>
		    			<td>Created</td>
		    			<td>{{instance.date_added|date:'d-m-y'}}</td>
		    		</tr>
		    		<tr>
		    			<td>Updated</td>
		    			<td>{{instance.date_updated|date:'d-m-y'|default:"-"}}</td>
		    		</tr>
		    </table>
	    </div>
	</div>
	<div class="card">
	    <div class="card-header">
	        <h3>Creator &amp; Updater <small></small></h3>
	    </div>
	    <div class="card-body">
		    <table class="table table-striped">
			    	<tr>
		    			<td>Creator</td>
		    			<td>{{instance.creator}}</td>
		    		</tr>
		    		<tr>
		    			<td>Updater</td>
		    			<td>{{instance.updater|default:"-"}}</td>
		    		</tr>
		    </table>
	    </div>
	</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}
                    

templates/cheques/view_cheques.html
{% extends "base.html" %}
{% load i18n %}


{% block headerbar %}
    <div id="header-bar" class="col-sm-12 clearfix">
        <h4 class="col-xs-4 col-sm-4">{{title}}</h4>
         <div class="btn-group pull-right">
              <a href="{% url 'cheques:create_cheque' %}" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-file visible-xs"></i><span class="hidden-xs">Create</span></a>
              <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter"><i class="glyphicon glyphicon-filter visible-xs"></i><span class="hidden-xs">Filter</span></button>
        </div>
    </div>
{% endblock %}

{% block filter %}
    <div id="filter" class="col-sm-3 col-md-2 collapse width">
        <div class="filter-content">
            <form action="{% url 'cheques:view_cheques' %}">
                <div class="row">
                    <label class="col-xs-12" for="filter_q">Query</label>
                    <input id="filter_q" type="text" name="q" placeholder="Enter Query..."/>
                </div>
                <section class="submitContainer">
                    <input type="submit" value="Filter" class="btn btn-primary" />
                </section>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}

    {% if message %}
        <div class="alert alert-success alert-dismissable fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{message}}
        </div>
    {% endif %}

    <div class="card">
                
        {% if instances %}
            
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Vendor</th>
                            <th>Cheque Number</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in instances %}
                        <tr class="check_items_row">
                            <td>{{instance.date|date:'d-m-y'}}</td>
                            <td><a href="{% url 'cheques:view_cheque' pk=instance.pk %}">{{instance.name}}</a></td>
                            <td><a href="{% url 'vendors:view_vendor' pk=instance.vendor.pk %}">{{instance.vendor.name|default:'-'}}</td>
                            <td>{{instance.cheque_number|default:'-'}}</td>
                            <td>{{instance.amount|default:"-"}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if instances.has_previous %}
                        <a href="?page={{ instances.previous_page_number }}{% if query %}&q={{query}}{% endif %}" class="glyphicon glyphicon-chevron-left">&nbsp;</a>
                    {% endif %}

                    <span class="current">
                        Page {{ instances.number }} of {{ instances.paginator.num_pages }}.
                    </span>

                    {% if instances.has_next %}
                        <a href="?page={{ instances.next_page_number }}{% if query %}&q={{query}}{% endif %}" class="glyphicon glyphicon-chevron-right">&nbsp;</a>
                    {% endif %}
                </span>
            </div>  
        {% else %}
            {% include 'includes/not_found.html' %}
        {% endif %}                       
    </div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}